[project]
name = "drogans-systemconf-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.3",
    "sqlalchemy>=2.0.41",
]
